services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4.8
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: "keycloak"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "keycloak"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    volumes:
      - ./.docker-compose/keycloak.env:/etc/secrets/keycloak.env
      - ./govuk/:/opt/keycloak/themes/govuk/
      - ./govuk-internal/:/opt/keycloak/themes/govuk-internal/
      - ./govuk-internal-cba/:/opt/keycloak/themes/govuk-internal-cba/
      - ./govuk-internal-dq/:/opt/keycloak/themes/govuk-internal-dq/
      - ./govuk-cop/:/opt/keycloak/themes/govuk-cop/
      - ./hmpo-lev/:/opt/keycloak/themes/hmpo-lev/
      - ./govuk-social-providers/:/opt/keycloak/themes/govuk-social-providers/
      - ./govuk-drt/:/opt/keycloak/themes/govuk-drt/
      - ./govuk-rscas/:/opt/keycloak/themes/govuk-rscas/
    command: start-dev
    depends_on:
      - mariadb
      - maildev

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.1.0
    ports:
      - "8081:80"
      - "25"
